version: "3"
services:
  ks-backend:
    container_name: ks-backend
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - ks-db
    tty: true
    stdin_open: true
  ks-db:
    container_name: ks-db
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  db-volume:
